language: ruby
rvm:
- 2.3.1
install:
- travis_retry bundle install
script: bundle exec rspec
notifications:
  slack: "$SLACK_TOKEN"
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: KZGdqCgmlAGQveK/b/bRSvUIO9wTlCUFngbmKLDHS9tf2gczBYNY3qnzD6GPJ7T12YFudWLH3W8D9CbRN6WyauwseKm+dRYVaeEg+tURobVD8FZgJBEaTnFr1EJNvb8x+iKxYjhV2XgCJHD6t7xbz+ONRVc71CrOi3qtVSRJKML2QocaUlgW+b6a7kMDT5/HtjOHipGf5MCXej+tlK1FESMYG5oNB/ogfbeDR928BCH7Kr4qtvndeF1QHwe5u4mD8UaVBPZNhm2ldEmxiI5+50B/BIjvX5afo0MPiWIJg+A3GlMpdQk4ETAxoT4WPyHYB4pjc2EwnEx9P7k1Zi/64oj+aAAwFlRw0Tof7GQ+zsFLtRSBGtKrWcmRU80iid0ATt+ZFBBNxZ8VDLRstm83wk5TShMPo2qil3eqvNzcvbbE4AwWdTDoky8Ipzto90RSFO1F2+8iLLC1+FLjKEwYakqdNhUz9ur2eVWWJFf2PHFpMDVDH907sRjFs2JaM81KJF4xuryPOlcvEFU/wlv42lSZ3oQPYH4TgV9PDYdcsFhmJkIIMb+RqAYn7PQYzwHUpEhklg0KaOns9hGi1V/iBE2X3Gy01QNITMtfSfIRGfHiFXEoHrXy7K9cZ0Zq2U7iaGsrQRAiv3zzz0FJ+uYH9nLXAC9U9UOUkqdGDNfbrl0=
  gem: orcid_client
  on:
    tags: true
    repo: datacite/orcid_client
